
import { createRoot } from 'react-dom/client'
import App from './App.tsx'
import './index.css'
import React from 'react'
import Ex_00_useState from './esercizi/00_useState/Ex_01_useState.tsx'
import Ex_01_useState from './esercizi/00_useState/Ex_02_useState.tsx'
import Ex_03_useState from './esercizi/00_useState/Ex_03_useState.tsx'
import Ex_04_useState from './esercizi/00_useState/Ex_04_useState.tsx'
import Ex_05_useState from './esercizi/00_useState/Ex_05_useState.tsx'
import Ex_06_useState from './esercizi/00_useState/Ex_06_useState.tsx'
import Ex_01_useEffect from './esercizi/01_useEffect/Ex_01_useEffect.tsx'
import Ex_02_useEffect from './esercizi/01_useEffect/Ex_02_useEffect.tsx'
import Ex_03_useEffect_axios from './esercizi/01_useEffect/Ex_03_useEffect_axios.tsx'
import Ex_01_useReducer from './esercizi/02_useReducer/Ex_01_useReducer.tsx'
import Ex__01_useEffect from './esercizi/01_useEffect/Ex__01_useEffect.tsx'
import Ex__02_useEffect from './esercizi/01_useEffect/Ex__02_useEffect.tsx'
import Ex__03_useEffect from './esercizi/01_useEffect/Ex__03_useEffect.tsx'
import Ex__05_useEffect from './esercizi/01_useEffect/Ex__05_useEffect.tsx'
import Ex_02_useReducer from './esercizi/02_useReducer/Ex_02_useReducer.tsx'
import Ex_03_useReducer from './esercizi/02_useReducer/Ex_03_useReducer.tsx'
import Ex_04_useReducer from './esercizi/02_useReducer/Ex_04_useReducer.tsx'
import Ex_05_useReducer from './esercizi/02_useReducer/Ex_05_useReducer.tsx'
import Ex_06_useReducer from './esercizi/02_useReducer/Ex_06_useReducer.tsx'
import Routing from './esercizi/03_Routing/Routing.tsx'
import Routing_useRoutes from './esercizi/03_Routing/Routing_useRoutes.tsx'
import Ex_01_useRef from './esercizi/04_useRef/Ex_01_useRef.tsx'
import Ex_08_useReducer_Marco_modificato from './esercizi/02_useReducer/Ex_08_useReducer_Marco_modificato.tsx'
import Ex_07_useReducer_Marco from './esercizi/02_useReducer/Ex_07_useReducer_Marco.tsx'
import Stopwatch_with_useRef from './esercizi/04_useRef/Ex_02_useRef.tsx'
import Stopwatch_without_useRef from './esercizi/04_useRef/Ex_03_useRef.tsx'
import Ex_04_useRef from './esercizi/04_useRef/Ex_04_useRef.tsx'
import Ex_05_useRef from './esercizi/04_useRef/Ex_05_useRef.tsx'
import Ex_06_useRef from './esercizi/04_useRef/Ex_06_useRef.tsx'
import Ex_07_useRef from './esercizi/04_useRef/Ex_07_useRef.tsx'
import Ex_01_props_drilling from './esercizi/05_props_drilling/Ex_01_props_drilling.tsx'
import Ex_02_props_drilling from './esercizi/05_props_drilling/Ex_02_props_drilling.tsx'
import Ex_02_props_drilling_ from './esercizi/05_props_drilling/Ex_02/Ex_02_props_drilling_.tsx'
import Ex_03_child_to_father from './esercizi/05_props_drilling/Ex_03_child_to_father.tsx'
import Ex_04_child_to_father from './esercizi/05_props_drilling/Ex_04_child_to_father.tsx'
import Ex_05_child_to_father from './esercizi/05_props_drilling/Ex_05_child_to_father.tsx'
import Ex_01_useContext from './esercizi/06_useContext/Ex_01_useContext/App.tsx'
import Ex_02_useContext from './esercizi/06_useContext/Ex_02_useContext/Ex_02_useContext.tsx'
import Ex_03_useContext from './esercizi/06_useContext/Ex_03_useContext/Ex_03_useContext.tsx'
import Ex_02_child_to_father from './esercizi/05_props_drilling/Ex_02_child_to_father.tsx'
import StyledApp from './esercizi/07_style/StyledApp.tsx'


createRoot(document.getElementById('root')!).render(
//  <Ex_01_props_drilling></Ex_01_props_drilling> 
 <Ex__02_useEffect></Ex__02_useEffect>
)

